/// CHANGE CONFIGURATION HERE!!
#undef CONFIG_EXAMPLE_USE_TFT
#define SUMP_OVER_UART 1
#undef  SCPI_ON_NETWORK
#undef SUMP_ON_NETWORK
#undef DEBUG_SUMP 
#define DEBUG_LOG_ENABLE 0

#define UART_TEST_OUTPUT 1
#undef RMT_PULSES
